### PR TITLE
Distinguish env differences in client

### PR DESCRIPTION
**Pull request by AndrewGibson27**
Description
-----------
This allows for specifying different config files for client-side code depending whether you're in a development vs. production environment.

Motivation and Context
----------------------
As this app grows, there will inevitably be more and more differences between production and development environments. Having a defined place to put these values will help maintainability.

How Has This Been Tested?
-------------------------
Here's how you can test these changes.
+ Delete `src/config.js`
+ Add `export API_BASE_URL=http://api.192.168.99.100.nip.io/` to `./config/ryr/ryr-env.sh`
+ `make` inside the `web` repository
+ Confirm `src/config.js` gets built and contains a line for `API_BASE_URL`
+ Run the app with `polymer serve` and make sure everything works.

Assuming production also has the environment variable `API_BASE_URL`, this will work there too.

Types of changes
----------------
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Code cleanup / Refactoring

Checklist:
----------
-  [] I have updated the documentation accordingly.

Fixes: https://github.com/request-yo-racks/web/issues/20

### CODE REVIEW

**Comment by rgreinho** [comment]
Awesome! That looks great!

Is there a way we could make this change more 12 factor compliant by using environment variables?

I tried this quickly, but could not make it work:
```
window.RYR_CONFIG = {
  GOOGLE_WEB_MAPS_API_KEY: process.env.RYR_GOOGLE_WEB_MAPS_API_KEY || '<redacted>',
  API_BASE: process.env.RYR_API_BASE || 'http://api.192.168.99.100.nip.io/'
};
```
`process` is not defined, but as polymer uses nodejs behind the scene, there must be a way to integrate it.

**Comment by rgreinho** [comment]
I just enabled CI for forks of the project, so if you could repush your branch it will trigger the CI and add update the check statuses.

**Comment by AndrewGibson27** [comment]
@rgreinho I just refactored this. Please see "has this been tested?" above for the updated steps.

**Comment by rgreinho** [comment]
The `Makefile` target `init-config` takes care of that for you locally( see https://github.com/request-yo-racks/web/blob/master/Makefile#L90-L91). In this CI, I simulated the setup by adding a few fake prep tasks (see https://github.com/request-yo-racks/web/blob/master/.circleci/config.yml#L19-L24).

**Comment by rgreinho** [comment]
@AndrewGibson27 I played with your PR here: https://github.com/request-yo-racks/web/pull/58. I rebased it on master and made some minor adjustments. For some reason it fails on Chrome :/

Here is the patch I applied:
```
﻿﻿diff --git a/.circleci/config.yml b/.circleci/config.yml
index a29a451..2fbb2d1 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,8 @@ jobs:
           name: Prepare the test environment
           command: |
             sudo mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
-            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'API_BASE_URL=http://api.192.168.99.100.nip.io/' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' >> ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
             sudo make bootstrap-npm setup
 
       - save_cache:
@@ -71,7 +72,8 @@ jobs:
           name: Prepare the test environment
           command: |
             sudo mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
-            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'API_BASE_URL=http://api.192.168.99.100.nip.io/' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' >> ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
             sudo make bootstrap-npm setup
 
       - save_cache:
diff --git a/.gitignore b/.gitignore
index 3f3ceae..a3165b8 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,4 +1,4 @@
 bower_components/
 build/
 node_modules/
-config/
+config.js
```

**Comment by rgreinho** [comment]
I fixed it! :)

Simply rebase on master and apply this patch:
```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index a29a451..2fbb2d1 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,8 @@ jobs:
           name: Prepare the test environment
           command: |
             sudo mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
-            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'API_BASE_URL=http://api.192.168.99.100.nip.io/' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' >> ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
             sudo make bootstrap-npm setup
 
       - save_cache:
@@ -71,7 +72,8 @@ jobs:
           name: Prepare the test environment
           command: |
             sudo mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
-            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'API_BASE_URL=http://api.192.168.99.100.nip.io/' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
+            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' >> ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
             sudo make bootstrap-npm setup
 
       - save_cache:
diff --git a/.gitignore b/.gitignore
index 3f3ceae..a3165b8 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,4 +1,4 @@
 bower_components/
 build/
 node_modules/
-config/
+config.js
diff --git a/src/ryr-location.html b/src/ryr-location.html
index ea96689..b5a5805 100644
--- a/src/ryr-location.html
+++ b/src/ryr-location.html
@@ -1,3 +1,5 @@
+<script type="text/javascript" src="./config.js"></script>
+
 <link rel="import" href="../bower_components/polymer/polymer-element.html">
 <link rel="import" href="../bower_components/google-map/google-map.html">
 <link rel="import" href="../bower_components/iron-ajax/iron-ajax.html">
@@ -82,6 +84,5 @@
     }
 
     window.customElements.define(RyrLocation.is, RyrLocation);
-
   </script>
-</dom-module>
+</dom-module>
\ No newline at end of file
```

That should do the trick! Good job!

**Pull request merged**
