### PR TITLE
Update header and footer

### PR DESCRIPTION
**Pull request by rgreinho**
Types of changes
----------------

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Code cleanup / Refactoring

Description
-----------

This patch updates the header and the footer to match the v2 design, as
well as ensuring that the interface stays responsive.

The app shell CSS was simplify to make sure it its maintenance will be
easy.

When switching to mobile mode, the menu is replaced by a drawer which contains the same items.

Desktop mode looks like this:
desktop - 640x360

Mobile mode looks like this:
mobile - 360x640

Footer looks like this:
footer

Motivation and Context
----------------------

Fulfill the v2 design.

How Has This Been Tested?
-------------------------

Manually.

Checklist:
----------

-  [] I have updated the documentation accordingly
-  [] I have written unit tests

Fixes request-yo-racks/web#77
Fixes request-yo-racks/web#101

### CODE REVIEW

**Comment by 2echoi** [comment]
Is there a reason to change the background color for "How It Workss" section from white to green? I thought we all agreed with the color.

And why is the color of Github icon purple? It doesn't seem right when the social media share has different colors on the footer.

**Comment by rgreinho** [comment]
The background of the "How it works section" is still green.

**Comment by rgreinho** [comment]
Good catch with the icon! It is purple because I visited the link before! I am going to adjust the CSS.

**Comment by rgreinho** [comment]
@2echoi The last commit fixes the visited links issue.

**Comment by 2echoi** [comment]
Hey Remy. Thanks for the update!

However, I felt the background color of "How It Works" section has to be white because the black font doesn't match the green color background. Also, if we want to go with the green background, then we have to switch the font color to white. However, I felt it is repetitive to use white-colored font since it has already used on the header.

**Comment by 2echoi** [comment]
Oh nevermind. This is the issue of focusing on header and footer. We'll deal with the others in the future!

**Pull request merged**
