### PR TITLE
Float clipboard to the right

### PR DESCRIPTION
**Pull request by arc6789**
Description
-----------

Moves copy clipboard to the right.

Motivation and Context
----------------------

Better user experience

Screenshots:
------------

Before:
screen shot 2018-02-25 at 10 19 35 pm

After:
screen shot 2018-02-25 at 10 19 11 pm

Types of changes
----------------

Visual change

### CODE REVIEW

**Comment by rgreinho** [comment]
As the preview box will expand to an unknown height (depending on the quantity of information retrieved), I think it makes more sense to have it top aligned. 

Unless you think of something which would look nicer that you'd like to implemet (feel free to experiment and move stuff around if you need to).

**Comment by arc6789** [comment]
Top aligned works fine but we can also have the clipboard positioned so that its bottom aligned no matter what the height of the preview box is.

I was actually visualizing the clipboard placed within the preview document at the bottom right corner. We can add padding to the document so it doesn't overlap with any text.

**Comment by rgreinho** [comment]
Oh that sounds good! Let's go with your idea!

**Comment by arc6789** [comment]
ok I just changed the placement of the clipboard. It wont be perfect until we actually add the email template

**Comment by rgreinho** [comment]
We actually have the email template already, but it gets populated only when you receive data from the API.

Here is what your change looks like:
image

And I like it :) Thanks for the work @arc6789 .

**Comment by arc6789** [comment]
more proof i should probably get that api running 😐

**Pull request merged**
